#not used with heroku
production:
  adapter: <%= ENV['DB_ADAPTER'] ||= 'postgresql' %>
  host: <%= ENV['OFN_DB_HOST'] ||= 'postgresql' %>
  encoding: unicode
  database: <%= ENV['OFN_DB'] ||= 'fhc_prod' %>
  pool: 5
  username: <%= ENV['OFN_DB_USER'] ||= 'fhc' %>
  password: <%= ENV['OFN_DB_PASS'] ||= 'f00d' %>
