development:
  adapter: postgresql
  encoding: unicode
  database: fhc_dev
  pool: 5
  host: localhost
  username: vagrant
  password: vagrant

test:
  adapter: postgresql
  encoding: unicode
  database: fhc_test<%= ENV['TEST_ENV_NUMBER'] %>
  pool: 5
  host: localhost
  username: vagrant
  password: vagrant

#not used with heroku
production:
  adapter: postgresql
  encoding: unicode
  database: fhc_prod
  pool: 5
  username: vagrant
  password: vagrant

staging:
  adapter: postgresql
  encoding: unicode
  database: fhc_prod
  pool: 5
  username: vagrant
  password: vagrant
